const EDIT_SIGN_UP_FORM = 'EDIT_SIGN_UP_FORM';
const REGISTER_USER = 'REGISTER_USER';
const REGISTER_FAILED = 'REGISTER_FAILED';

export default {
  EDIT_SIGN_UP_FORM,
  REGISTER_USER,
  REGISTER_FAILED,
};
