const EDIT_SIGN_IN_FORM = 'EDIT_SIGN_IN_FORM';
const AUTHORIZE_USER = 'AUTHORIZE_USER';
const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';
const REMOVE_ERROR = 'REMOVE_ERROR';
const LOG_OUT = 'LOG_OUT';
const UPDATE_USER = 'UPDATE_USER';
const UPLOAD_USER_FROM_LOCAL_STORAGE = 'UPLOAD_USER_FROM_LOCAL_STORAGE';

export default {
  EDIT_SIGN_IN_FORM,
  AUTHORIZE_USER,
  AUTHORIZATION_ERROR,
  REMOVE_ERROR,
  LOG_OUT,
  UPDATE_USER,
  UPLOAD_USER_FROM_LOCAL_STORAGE,
};
